// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

type (
	IHello interface {
		SayHello() string
	}
)

var (
	localHello IHello
)

func Hello() IHello {
	if localHello == nil {
		panic("implement not found for interface IHello, forgot register?")
	}
	return localHello
}

func RegisterHello(i IHello) {
	localHello = i
}
